### ISSUE TITLE
Deserialization

### ISSUE THREAD

**Issue by pckilgore** [pckilgore/reason-cognito#8]
We do a lot of JSON deserialization and serialization.

Right now we do it in two ways:
  1. Type un-safely (%identity / @bs magic)
  2. Annoyingly-boilerplate deserializers.

Based on research* there are a few solutions to investigate:
  1. https://github.com/ryb73/ppx_decco
  2. https://github.com/jaredly/milk

To resolve this issue:
1. [x] Investigate further options.
2. [x] Implement options on a good middle-ground case, `type signUpResponse`
   * [X] hand-written deserializer https://github.com/pckilgore/reason-cognito/blob/af8cfaa4e8cdc86d55392fb0cc48b9c9d1a969b5/src/Cognito.re#L135-L186
   * [x] milk (wraps several options below)
     * [x] https://github.com/jaredly/rex-json
     * [x] bs_json
     * [x] yojson
   * [x] ppx_decco
   * [x] https://github.com/ahrefs/atdgen-workshop-starter/blob/master/README.md
3. [ ] Choose path forward

\* complaining into the twitter void

**Comment by pckilgore** [comment]
I'm going to look into Milk for now...

**Comment by pckilgore** [comment]
Note to self: Check licenses.  bs-json appears to be copyleft, which isn't ideal for a library I'd like to be consumable by private projects.

**Comment by pckilgore** [comment]
Ehh MPL 2.0 looks fine, and we can relicense this work under the MIT which is ideal IMO.

**Comment by pckilgore** [comment]
Milk is really rough so far, althought it's certainly the path of least resistance if I can get it to work...

**Comment by pckilgore** [comment]
Heck no.  If I were to use a GPLv3 (copy-left) library as part of a piece of a project, I am required by that license to open source that derivative work, and license that derivative work under the GPLv3.  And since it is unlikely a company would agree to that, and since I want people to be able to consume this project commercially, I can't license this project under an aggressive copyleft license.  And since I don't want to license **this** project under an aggressive copyleft license, I can't use any aggressive copyleft licensed library as part of this project.

Most things are MIT or ISC which are very very permissive and require not a lot of thought to use.  So anything NOT MIT/ISC, I make sure I understand what I'm getting into.

**Comment by pckilgore** [comment]
So I ran into issues with Milk that never were resolved:
https://twitter.com/0xPCK/status/1183563698822090754

ppx_decco looks cool but it's too magic for me right now, and I read somewhere to avoid piling on ppx until you understand what they do and how they might break (and I don't, yet).

Then I tried atdgen and it _just worked_ so that's what I want to use until I have a good reason not to do so.  Right now, the only reason i see is that  I don't quite understand the error handling story there, but damn, it's so easy I just don't care.

**Comment by pckilgore** [comment]
ref f37f92a

**Comment by idkjs** [comment]
atdgen is for real by some serious ocaml devs too.

**Comment by idkjs** [comment]
Tried running. I am getting user already exists for every variation of my email address. So this isnt working:
```reason
let emailAttribute = Js.Dict.empty();
Js.Dict.set(emailAttribute, "Name", "email");
Js.Dict.set(emailAttribute, "Value", "a.a.r.m.a.n.d.i.n.b.o.x@gmail.com");
```

Either I used all the variations or you configured it somehow to read all the variations as the same address. If its the latter, can you tell me how you did that? 

If not, can you clear out the test userpool?

Peace to you, brother! Glad to have you back!

**Comment by idkjs** [comment]
Or I just need to change the name from sarah7 to sarah77. So `user already exists` means the username is already in use. That error message could be more clear, I guess.
